version: '3.9'

services:
  db:
    image: postgres:latest
    container_name: Postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    expose:
      - 5432

volumes:
  db:
    driver: local
